Version: 1.8 # minimal SMASH version to use with this config file

Logging:
    default: INFO

General:
    Modus:          Collider
    Time_Step_Mode: None
    End_Time:       200.0
    Randomseed:     -1
    Nevents:        120

Output:
    Collisions:
        Format:          ["Oscar2013"]

Modi:
    Collider:
        Projectile:
            Particles: {2212: 82, 2112: 126} #Lead208
        Target:
            Particles: {2212: 82, 2112: 126} #Lead208

        Sqrtsnn: 200
        Fermi_Motion: "frozen"
        Impact:
            Range: [0,3.3]
